PROCESS BEFORE OUTPUT.
*&SPWIZARD: PBO FLOW LOGIC FOR TABLECONTROL 'TC_TAXDATA'
  MODULE tc_taxdata_change_tc_attr.
*&SPWIZARD: MODULE TC_TAXDATA_CHANGE_COL_ATTR.
  LOOP AT   ttax
       INTO wtax
       WITH CONTROL tc_taxdata
       CURSOR tc_taxdata-current_line.
*&SPWIZARD:   MODULE TC_TAXDATA_CHANGE_FIELD_ATTR
  ENDLOOP.

* MODULE STATUS_0110.
*
PROCESS AFTER INPUT.
*&SPWIZARD: PAI FLOW LOGIC FOR TABLECONTROL 'TC_TAXDATA'
  LOOP AT ttax.
    CHAIN.
      FIELD wtax-shkzg.
      FIELD wtax-tax_code.
      FIELD wtax-tax_amount.
      MODULE tc_taxdata_modify ON CHAIN-REQUEST.
    ENDCHAIN.
    FIELD wtax-sel
      MODULE tc_taxdata_mark ON REQUEST.
  ENDLOOP.
*&SPWIZARD: MODULE TC_TAXDATA_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE TC_TAXDATA_CHANGE_COL_ATTR.

PROCESS ON VALUE-REQUEST.
  FIELD wtax-tax_code  MODULE f4_mwskz.
