*&---------------------------------------------------------------------*
*& Include ZMYCST_INVOICE_YC_DATA_HEAD
*&---------------------------------------------------------------------*

*&SPWIZARD: FUNCTION CODES FOR TABSTRIP 'TABHEAD'
CONSTANTS: BEGIN OF C_TABHEAD,
             TAB1 LIKE SY-UCOMM VALUE 'TABHEAD_FC1',
             TAB2 LIKE SY-UCOMM VALUE 'TABHEAD_FC2',
             TAB3 LIKE SY-UCOMM VALUE 'TABHEAD_FC3',
             TAB4 LIKE SY-UCOMM VALUE 'TABHEAD_FC4',
           END OF C_TABHEAD.
*&SPWIZARD: DATA FOR TABSTRIP 'TABHEAD'
CONTROLS:  TABHEAD TYPE TABSTRIP.
DATA:      BEGIN OF G_TABHEAD,
             SUBSCREEN   LIKE SY-DYNNR,
             PROG        LIKE SY-REPID VALUE 'ZMYCST_INVOICE_YC',
             PRESSED_TAB LIKE SY-UCOMM VALUE C_TABHEAD-TAB1,
           END OF G_TABHEAD.

*&SPWIZARD: OUTPUT MODULE FOR TS 'TABHEAD'. DO NOT CHANGE THIS LINE!
*&SPWIZARD: SETS ACTIVE TAB
MODULE TABHEAD_ACTIVE_TAB_SET OUTPUT.
  TABHEAD-ACTIVETAB = G_TABHEAD-PRESSED_TAB.
  CASE G_TABHEAD-PRESSED_TAB.
    WHEN C_TABHEAD-TAB1.
      G_TABHEAD-SUBSCREEN = '9201'.
    WHEN C_TABHEAD-TAB2.
      G_TABHEAD-SUBSCREEN = '9202'.
    WHEN C_TABHEAD-TAB3.
      G_TABHEAD-SUBSCREEN = '9203'.
    WHEN C_TABHEAD-TAB4.
      G_TABHEAD-SUBSCREEN = '9204'.
    WHEN OTHERS.
*&SPWIZARD:      DO NOTHING
  ENDCASE.
ENDMODULE.

*&SPWIZARD: INPUT MODULE FOR TS 'TABHEAD'. DO NOT CHANGE THIS LINE!
*&SPWIZARD: GETS ACTIVE TAB
MODULE TABHEAD_ACTIVE_TAB_GET INPUT.
  OK_CODE = SY-UCOMM.
  CASE OK_CODE.
    WHEN C_TABHEAD-TAB1.
      G_TABHEAD-PRESSED_TAB = C_TABHEAD-TAB1.
    WHEN C_TABHEAD-TAB2.
      G_TABHEAD-PRESSED_TAB = C_TABHEAD-TAB2.
    WHEN C_TABHEAD-TAB3.
      G_TABHEAD-PRESSED_TAB = C_TABHEAD-TAB3.
    WHEN C_TABHEAD-TAB4.
      G_TABHEAD-PRESSED_TAB = C_TABHEAD-TAB4.
    WHEN OTHERS.
*&SPWIZARD:      DO NOTHING
  ENDCASE.
ENDMODULE.
