*&---------------------------------------------------------------------*
*& Include ZMYCST_INVOICE_YC_TAX
*&---------------------------------------------------------------------*

*&SPWIZARD: DECLARATION OF TABLECONTROL 'TC_TAXDATA' ITSELF
CONTROLS: TC_TAXDATA TYPE TABLEVIEW USING SCREEN 9203.

*&SPWIZARD: OUTPUT MODULE FOR TC 'TC_TAXDATA'. DO NOT CHANGE THIS LINE!
*&SPWIZARD: UPDATE LINES FOR EQUIVALENT SCROLLBAR
MODULE TC_TAXDATA_CHANGE_TC_ATTR OUTPUT.
  DESCRIBE TABLE TTAX LINES TC_TAXDATA-lines.
ENDMODULE.

*&SPWIZARD: INPUT MODULE FOR TC 'TC_TAXDATA'. DO NOT CHANGE THIS LINE!
*&SPWIZARD: MODIFY TABLE
MODULE TC_TAXDATA_MODIFY INPUT.
  MODIFY TTAX
    FROM WTAX
    INDEX TC_TAXDATA-CURRENT_LINE.
ENDMODULE.

*&SPWIZARD: INPUT MODUL FOR TC 'TC_TAXDATA'. DO NOT CHANGE THIS LINE!
*&SPWIZARD: MARK TABLE
MODULE TC_TAXDATA_MARK INPUT.
  DATA: g_TC_TAXDATA_wa2 like line of TTAX.
    if TC_TAXDATA-line_sel_mode = 1
    and WTAX-SEL = 'X'.
     loop at TTAX into g_TC_TAXDATA_wa2
       where SEL = 'X'.
       g_TC_TAXDATA_wa2-SEL = ''.
       modify TTAX
         from g_TC_TAXDATA_wa2
         transporting SEL.
     endloop.
  endif.
  MODIFY TTAX
    FROM WTAX
    INDEX TC_TAXDATA-CURRENT_LINE
    TRANSPORTING SEL.
ENDMODULE.
