PROCESS BEFORE OUTPUT.
*&SPWIZARD: PBO FLOW LOGIC FOR TABSTRIP 'TABITEM'
  MODULE TABITEM_ACTIVE_TAB_SET.
  CALL SUBSCREEN TABITEM_SCA
    INCLUDING G_TABITEM-PROG G_TABITEM-SUBSCREEN.
*  MODULE status_0900.
*  MODULE mir7.

PROCESS AFTER INPUT.
*&SPWIZARD: PAI FLOW LOGIC FOR TABSTRIP 'TABITEM'
  CALL SUBSCREEN TABITEM_SCA.
  MODULE TABITEM_ACTIVE_TAB_GET.
*  MODULE user_command_0900.
