PROCESS BEFORE OUTPUT.
*&SPWIZARD: PBO FLOW LOGIC FOR TABSTRIP 'TABHEAD'
  MODULE TABHEAD_ACTIVE_TAB_SET.
  CALL SUBSCREEN TABHEAD_SCA
    INCLUDING G_TABHEAD-PROG G_TABHEAD-SUBSCREEN.
*  MODULE status_0900.
*  MODULE mir7.

PROCESS AFTER INPUT.
*&SPWIZARD: PAI FLOW LOGIC FOR TABSTRIP 'TABHEAD'
  CALL SUBSCREEN TABHEAD_SCA.
  MODULE TABHEAD_ACTIVE_TAB_GET.
*  MODULE user_command_0900.
