PROCESS BEFORE OUTPUT.
*&SPWIZARD: PBO FLOW LOGIC FOR TABLECONTROL 'TC_TAXDATA'
  MODULE TC_TAXDATA_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE TC_TAXDATA_CHANGE_COL_ATTR.
  LOOP AT   TTAX
       INTO WTAX
       WITH CONTROL TC_TAXDATA
       CURSOR TC_TAXDATA-CURRENT_LINE.
*&SPWIZARD:   MODULE TC_TAXDATA_CHANGE_FIELD_ATTR
  ENDLOOP.

* MODULE STATUS_0110.
*
PROCESS AFTER INPUT.
*&SPWIZARD: PAI FLOW LOGIC FOR TABLECONTROL 'TC_TAXDATA'
  LOOP AT TTAX.
    CHAIN.
      FIELD WTAX-SHKZG.
      FIELD WTAX-TAX_CODE.
      FIELD WTAX-TAX_AMOUNT.
      MODULE TC_TAXDATA_MODIFY ON CHAIN-REQUEST.
    endchain.
    FIELD WTAX-SEL
      MODULE TC_TAXDATA_MARK ON REQUEST.
  ENDLOOP.
*&SPWIZARD: MODULE TC_TAXDATA_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE TC_TAXDATA_CHANGE_COL_ATTR.

* MODULE USER_COMMAND_0110.
