*&---------------------------------------------------------------------*
*& Include ZMYCST_INVOICE_YC_DATA_ITEM
*&---------------------------------------------------------------------*

*&SPWIZARD: FUNCTION CODES FOR TABSTRIP 'TABITEM'
CONSTANTS: BEGIN OF C_TABITEM,
             TAB1 LIKE SY-UCOMM VALUE 'TABITEM_FC1',
             TAB2 LIKE SY-UCOMM VALUE 'TABITEM_FC2',
           END OF C_TABITEM.
*&SPWIZARD: DATA FOR TABSTRIP 'TABITEM'
CONTROLS:  TABITEM TYPE TABSTRIP.
DATA:      BEGIN OF G_TABITEM,
             SUBSCREEN   LIKE SY-DYNNR,
             PROG        LIKE SY-REPID VALUE 'ZMYCST_INVOICE_YC',
             PRESSED_TAB LIKE SY-UCOMM VALUE C_TABITEM-TAB1,
           END OF G_TABITEM.

*&SPWIZARD: OUTPUT MODULE FOR TS 'TABITEM'. DO NOT CHANGE THIS LINE!
*&SPWIZARD: SETS ACTIVE TAB
MODULE TABITEM_ACTIVE_TAB_SET OUTPUT.
  TABITEM-ACTIVETAB = G_TABITEM-PRESSED_TAB.
  CASE G_TABITEM-PRESSED_TAB.
    WHEN C_TABITEM-TAB1.
      G_TABITEM-SUBSCREEN = '9301'.
    WHEN C_TABITEM-TAB2.
      G_TABITEM-SUBSCREEN = '9302'.
    WHEN OTHERS.
*&SPWIZARD:      DO NOTHING
  ENDCASE.
ENDMODULE.

*&SPWIZARD: INPUT MODULE FOR TS 'TABITEM'. DO NOT CHANGE THIS LINE!
*&SPWIZARD: GETS ACTIVE TAB
MODULE TABITEM_ACTIVE_TAB_GET INPUT.
  OK_CODE = SY-UCOMM.
  CASE OK_CODE.
    WHEN C_TABITEM-TAB1.
      G_TABITEM-PRESSED_TAB = C_TABITEM-TAB1.
    WHEN C_TABITEM-TAB2.
      G_TABITEM-PRESSED_TAB = C_TABITEM-TAB2.
    WHEN OTHERS.
*&SPWIZARD:      DO NOTHING
  ENDCASE.
ENDMODULE.
